### PR TITLE
chore(deps): update dependency hono to v3.11.3

### PR DESCRIPTION
**Pull request by douglasduteil**
Hi

Here is a PR to test if this lib is still compatible with with hono now a days.
Locally I have an issue with mismatching Context so this pr might resolve it by ensuring that this lib is using the same hono latest version

### CODE REVIEW

**Comment by douglasduteil** [comment]
Might be unnecessary as one can use "overrides" in `package.josn` to sync the fixed version

**Comment by jcs224** [comment]
Yeah, I'm trying to figure out the right strategy for version-matching with upstream Hono. The difficulty is Hono ships so many updates, I can't keep up with them all :sweat_smile: but the API for middleware seems to remain consistent. As soon as that's not the case, I will of course update the library to accommodate.

**Comment by douglasduteil** [comment]
Hi @jcs224 
I would suggest using our friendly https://docs.renovatebot.com/modules/datasource/deno/ which is highly adaptable :)

**Comment by jcs224** [comment]
> Hi @jcs224 I would suggest using our friendly https://docs.renovatebot.com/modules/datasource/deno/ which is highly adaptable :)

Interesting! I will look into this

**Pull request closed without merging**
